import { type NextPage } from "next";
import Head from "next/head";
import React from "react";
import { EmployeeTable } from "../components/EmployeesTable";
import { EmployeeFormModal } from "../components/Modal";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const [isModalOpen, setIsModalOpen] = React.useState(false);
  const utils = trpc.useContext();
  const { mutate } = trpc.employees.addEmployee.useMutation({
    onSettled() {
      utils.employees.allEmployees.invalidate();
    },
  });
  return (
    <>
      <Head>
        <title>Nailted Test</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-slate-900">
        {/* <button
          className="btn text-white"
          onClick={() =>
            mutate({
              name: "Roland",
              surname: "Bayor",
              address: "12 bungalow",
              birthdate: "12/01/1998",
              email: "rb@gmail/com",
              phone: "0540935429",
            })
          }
        >
          Add Entry
        </button> */}
        <button className="btn text-white" onClick={() => setIsModalOpen(true)}>
          Add Entry
        </button>

        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <EmployeeTable />
        </div>
      </main>
      <EmployeeFormModal
        handleModalClose={() => setIsModalOpen(false)}
        isOpen={isModalOpen}
      ></EmployeeFormModal>
    </>
  );
};

export default Home;
