import { type NextPage } from "next";
import Head from "next/head";
import React from "react";
import { ToastContainer } from "react-toastify";
import { EmployeeFormModal } from "../components/EmployeeFormModal";
import { EmployeeTable } from "../components/EmployeesTable";

import "react-toastify/dist/ReactToastify.css";

const Home: NextPage = () => {
  const [isModalOpen, setIsModalOpen] = React.useState(false);

  return (
    <>
      <Head>
        <title>Nailted Test</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-slate-900">
        <ToastContainer />

        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <button
            className="rounded bg-green-600 p-3 text-white hover:bg-green-700"
            onClick={() => setIsModalOpen(true)}
          >
            Add Entry
          </button>
          <EmployeeTable />
        </div>
      </main>
      <EmployeeFormModal
        handleModalClose={() => setIsModalOpen(false)}
        isOpen={isModalOpen}
      ></EmployeeFormModal>
    </>
  );
};

export default Home;
